//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.10.14 at 07:43:51 PM IST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.democode.com/soapApp/wsdl", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package wsdl;
